/*PRIMARIAS*/

ALTER TABLE Pedidos ADD CONSTRAINT PK_PEDIDOS_ID
    PRIMARY KEY (pedidoID);

ALTER TABLE Contenidos ADD CONSTRAINT PK_CONTENIDOS_PRODUCTOPEDIDO 
    PRIMARY KEY (codigoProducto, codigoPedido);

ALTER TABLE Productos ADD CONSTRAINT PK_PRODUCTOS_CODIGO 
    PRIMARY KEY (codigo);

ALTER TABLE PollosEnteros ADD CONSTRAINT PK_POLLOSENTEROS_CODIGO 
    PRIMARY KEY (codigo);

ALTER TABLE PollosDespresados ADD CONSTRAINT PK_POLLOSDESPRESADOS_CODIGO 
    PRIMARY KEY (codigo);

ALTER TABLE Menudencias ADD CONSTRAINT PK_MENUDENCIAS_CODIGO 
    PRIMARY KEY (codigo);

ALTER TABLE Clientes ADD CONSTRAINT PK_CLIENTE_ID
    PRIMARY KEY (clienteID);

ALTER TABLE PuntosDeVenta ADD CONSTRAINT PK_PUNTOVENTA_CODIGO 
    PRIMARY KEY (codigoCliente);

ALTER TABLE Externos ADD CONSTRAINT PK_EXTERNOS_CODIGO 
    PRIMARY KEY (codigoCliente);

ALTER TABLE Telefonos ADD CONSTRAINT PK_TELEFONOS_CODIGO 
    PRIMARY KEY (numeroTelefonico);

ALTER TABLE Facturas ADD CONSTRAINT PK_FACTURAS_ID 
    PRIMARY KEY (facturaID);

ALTER TABLE Fisicas ADD CONSTRAINT PK_FISICAS_CODIGO
    PRIMARY KEY (codigoFactura);

ALTER TABLE Electronicas ADD CONSTRAINT PK_ELECTRONICAS_CODIGO 
    PRIMARY KEY (codigoFactura);

ALTER TABLE Deudas ADD CONSTRAINT PK_DEUDAS_ID
    PRIMARY KEY (deudaID);

ALTER TABLE Pagos ADD CONSTRAINT PK_PAGOS_ID
    PRIMARY KEY (pagoID);

ALTER TABLE Despachos ADD CONSTRAINT PK_DESPACHOS_ID
    PRIMARY KEY (despachoID);

ALTER TABLE Envios ADD CONSTRAINT PK_ENVIOS_ID
    PRIMARY KEY (guiaID);

ALTER TABLE Paradas ADD CONSTRAINT PK_PARADAS_ID
    PRIMARY KEY (rutaID, codigoEnvio);