/* XDisparadores */


DROP TRIGGER TR_PRODUCTOEXCLUSIVO_POLLOSENTEROS;
DROP TRIGGER TR_PRODUCTOEXCLUSIVO_POLLOSDESPRESADOS;
DROP TRIGGER TR_PRODUCTOEXCLUSIVO_MENUDENCIAS;
DROP TRIGGER TR_FACTURAEXCLUSIVA_FISICAS;
DROP TRIGGER TR_FACTURAEXCLUSIVA_ELECTRONICAS;
DROP TRIGGER TR_CLIENTEEXCLUSIVO_PUNTOSDEVENTA;
DROP TRIGGER TR_CLIENTEEXCLUSIVO_EXTERNOS;

DROP TRIGGER TR_PRODUCTO_PRECIO_VALIDO;
DROP TRIGGER TR_PRODUCTO_PESO_VALIDO;
DROP TRIGGER TR_PRODUCTO_MODIFICACION_RESTRINGIDA;
DROP TRIGGER TR_PRODUCTO_ELIMINACION_RESTRINGIDA;

DROP TRIGGER TR_DESPACHO_FACTURA_CANCELADA;
DROP TRIGGER TR_ENVIO_DEVUELTO_OBSERVACIONES;
DROP TRIGGER TR_ENVIO_ADICION_RESTRICCION;
DROP TRIGGER TR_DESPACHO_MODIFICACION_RESTRINGIDA;

DROP TRIGGER TR_PEDIDOS_ID_BI;
DROP TRIGGER TR_PEDIDOS_FACTURADOS_BU;
DROP TRIGGER TR_PEDIDOS_PAGO_BD;


DROP TRIGGER TR_FACTURAS_ID_BI;
DROP TRIGGER TR_PAGOS_SALDO_PENDIENTE_BI;
DROP TRIGGER TR_FACTURAS_PENDIENTES_BU;
DROP TRIGGER TR_FACTURAS_DEUDA_BU;


DROP TRIGGER TR_CLIENTES_BU;
DROP TRIGGER TR_CLIENTES_ELIMINAR_BD;


