/*Foraneas*/

ALTER TABLE Pedidos ADD CONSTRAINT FK_PEDIDOS_CLIENTES 
    FOREIGN KEY (codigoCliente) REFERENCES Clientes(clienteID);

ALTER TABLE Contenidos ADD CONSTRAINT FK_CONTENIDOS_PEDIDOS
    FOREIGN KEY (codigoPedido) REFERENCES Pedidos(pedidoID);

ALTER TABLE Contenidos ADD CONSTRAINT FK_CONTENIDOS_PRODUCTOS
    FOREIGN KEY (codigoProducto) REFERENCES Productos(codigo);

ALTER TABLE Productos ADD CONSTRAINT FK_PRODUCTOS_PEDIDOS
    FOREIGN KEY (codigoPedido) REFERENCES Pedidos(pedidoID);

ALTER TABLE PollosEnteros ADD CONSTRAINT FK_ENTEROS_PRODUCTOS
    FOREIGN KEY (codigo) REFERENCES Productos(codigo);

ALTER TABLE PollosDespresados ADD CONSTRAINT FK_DESPRESADOS_PRODUCTOS
    FOREIGN KEY (codigo) REFERENCES Productos(codigo);

ALTER TABLE Menudencias ADD CONSTRAINT FK_MENUDENCIAS_PRODUCTOS
    FOREIGN KEY (codigo) REFERENCES Productos(codigo);

ALTER TABLE PuntosDeVenta ADD CONSTRAINT FK_PUNTOS_CLIENTES
    FOREIGN KEY (codigoCliente) REFERENCES Clientes(clienteID);

ALTER TABLE Externos ADD CONSTRAINT FK_EXTERNOS_CLIENTES
    FOREIGN KEY (codigoCliente) REFERENCES Clientes(clienteID);

ALTER TABLE Telefonos ADD CONSTRAINT FK_TELEFONOS_CLIENTES
    FOREIGN KEY (tclienteID) REFERENCES Clientes(clienteID);

ALTER TABLE Facturas ADD CONSTRAINT FK_FACTURAS_PEDIDOS
    FOREIGN KEY (codigoPedido) REFERENCES Pedidos(pedidoID);

ALTER TABLE Facturas ADD CONSTRAINT FK_FACTURAS_DEUDA
    FOREIGN KEY (codigoDeuda) REFERENCES Deudas(deudaID);

ALTER TABLE Facturas ADD CONSTRAINT FK_FACTURAS_PAGOS
    FOREIGN KEY (codigoPago) REFERENCES Pagos(pagoID);

ALTER TABLE Fisicas ADD CONSTRAINT FK_FISICAS_FACTURAS
    FOREIGN KEY (codigoFactura) REFERENCES Facturas(facturaID);

ALTER TABLE Electronicas ADD CONSTRAINT FK_ELECTRONICAS_FACTURAS
    FOREIGN KEY (codigoFactura) REFERENCES Facturas(facturaID);

ALTER TABLE Despachos ADD CONSTRAINT FK_DESPACHOS_FACTURAS
    FOREIGN KEY (codigoFactura) REFERENCES Facturas(facturaID);

ALTER TABLE Envios ADD CONSTRAINT FK_ENVIOS_DESPACHOS
    FOREIGN KEY (idDespacho) REFERENCES Despachos(despachoID);

ALTER TABLE Paradas ADD CONSTRAINT FK_PARADAS_ENVIOS
    FOREIGN KEY (codigoEnvio) REFERENCES Envios(guiaID);

