/*UNICAS*/

ALTER TABLE Envios ADD CONSTRAINT UQ_ENVIOS_PLACA
    UNIQUE (placaVehiculo);

ALTER TABLE Clientes ADD CONSTRAINT UQ_CLIENTE_NIT
    UNIQUE (nit);

ALTER TABLE Facturas ADD CONSTRAINT UQ_FACTURAS_BOLETA
    UNIQUE (nit);

ALTER TABLE Externos ADD CONSTRAINT UQ_EXTERNOS_CORREO
    UNIQUE (correoElectronico);