/*XPoblar*/

TRUNCATE TABLE Pedidos;
TRUNCATE TABLE Contenidos;
TRUNCATE TABLE Productos;
TRUNCATE TABLE PollosEnteros;
TRUNCATE TABLE PollosDespresados;
TRUNCATE TABLE Menudencias;
TRUNCATE TABLE Clientes;
TRUNCATE TABLE PuntosDeVenta;
TRUNCATE TABLE Externos;
TRUNCATE TABLE Telefonos;
TRUNCATE TABLE Facturas;
TRUNCATE TABLE Fisicas;
TRUNCATE TABLE Electronicas;
TRUNCATE TABLE Deudas;
TRUNCATE TABLE Pagos;
TRUNCATE TABLE Despachos;
TRUNCATE TABLE Envios;
TRUNCATE TABLE Paradas;